#user interface for London Shiny
library(plotly)
library(leaflet)
library(sp)
library(maptools)
library(RColorBrewer)
library(maptools)
library(rgdal)
library(classInt)
library(shiny)
library(shinythemes)

source("dataloader.r")

nombres <- c("Población","Area en Km^2 de la sección censal","Densidad de población en pers/Km^2","Código postal","Nombre distrito",
  "Total población",
  "Total hombres" ,
  "Total mujeres" ,
  "Pers. de menos de 16 años" ,
  "Pers. entre 16 y 64 años" ,
  "Pers. con más de 64 años" ,
  "Pers. que han nacido en España" ,
  "Pers. con nacionalidad española que han nacido en España" ,
  "Pers. con nacionalidad Española" ,
  "Pers. con nacionalidad extranjera" ,
  "Hombres de menos de 16 años" ,
  "Hombres entre 16 y 64 años" ,
  "Hombres con más de 64 años" ,
  "Mujeres de menos de 16 años" ,
  "Mujeres entre 16 y 64 años" ,
  "Mujeres con más de 64 años" ,
  "Hombres con nacionalidad española" ,
  "Hombres con nacionalidad extranjera" ,
  "Mujeres con nacionalidad española" ,
  "Mujeres con nacionalidad extranjera" ,
  "Pers. de nacionalidad española de menos de 16 años" ,
  "Pers. de nacionalidad extranjera de menos de 16 años" ,
  "Pers. de nacionalidad española entre 16 y 64 años" ,
  "Pers. de nacionalidad extranjera entre 16 y 64 años" ,
  "Pers. de nacionalidad española con más de 64 años" ,
  "Pers. de nacionalidad extranjera con más de 64 años" ,
  "Pers. con estado civil soltero" ,
  "Pers. con estado civil casado" ,
  "Pers. con estado civil separado" ,
  "Pers. con estado civil divorciado" ,
  "Pers. con estado civil viudo" ,
  "Pers. analfabetas" ,
  "Pers. sin estudios" ,
  "Pers. con estudios de primer grado" ,
  "Pers. con estudios de segundo grado" ,
  "Pers. con estudios de tercer grado" ,
  "Pers. sin información sobre su nivel de estudios (menores de 16 años " ,
  "Hombres analfabetos" ,
  "Mujeres analfabetas" ,
  "Hombres sin estudios" ,
  "Mujeres sin estudios" ,
  "Hombres con estudios de primer grado" ,
  "Mujeres con estudios de primer grado" ,
  "Hombres con estudios de segundo grado" ,
  "Mujeres con estudios de segundo grado" ,
  "Hombres con estudios de tercer grado" ,
  "Mujeres con estudios de tercer grado" ,
  "Hombres sin información sobre su nivel de estudios (menores de 16 años " ,
  "Mujeres sin información sobre su nivel de estudios (menores de 16 años " ,
  "Mujeres sin información sobre su nivel de estudios (menores de 16 años " ,
  "Pers. de nacionalidad extranjera y analfabetas" ,
  "Pers. de nacionalidad espaÃ±ola sin estudios" ,
  "Pers. de nacionalidad extranjera sin estudios" ,
  "Pers. de nacionalidad extranjera sin estudios" ,
  "Pers. de nacionalidad extranjera con estudios de primer grado" ,
  "Pers. de nacionalidad española con estudios de segundo grado" ,
  "Pers. de nacionalidad española con estudios de segundo grado" ,
  "Pers. de nacionalidad española con estudios de tercer grado" ,
  "Pers. de nacionalidad extranjera con estudios de tercer grado" ,
  "Pers. de nacionalidad española sin información sobre su nivel de estudios (menores de 16 años " ,
  "Pers. entre 16 y 64 años con estudios de segundo grado" ,
  "Pers. con más de 64 años con estudios de segundo grado" ,
  "Pers. entre 16 y 64 años con estudios de tercer grado" ,
  "Pers. con más de 64 años con estudios de tercer grado" ,
  "Pers. de menos de 16 años (no se dispone de información sobre su nivel de estudios " ,
  "Total Viviendas" ,
  "Viviendas Principales" ,
  "Viviendas Secundarias" ,
  "Viviendas Vacías" ,
  "Viviendas en propiedad, por compra, totalmente pagada" ,
  "Viviendas en propiedad, por compra, con pagos pendientes" ,
  "Viviendas en propiedad, por herencia o donación" ,
  "Viviendas en alquiler" ,
  "Viviendas cedida gratis o a bajo precio" ,
  "Viviendas en otro tipo de régimen de tenencia" ,
  "Viviendas de menos de 30m2" ,
  "Viviendas entre 30-45 m2" ,
  "Viviendas entre 46-60 m2" ,
  "Viviendas entre 61-75 m2" ,
  "Viviendas entre 76-90 m2" ,
  "Viviendas entre 76-90 m2" ,
  "Viviendas entre 106-120 m2" ,
  "Viviendas entre 121-150 m2" ,
  "Viviendas entre 121-150 m2" ,
  "Viviendas de más de 180 m2" ,
  "Viviendas con 1 habitación" ,
  "Viviendas con 2 habitaciones" ,
  "Viviendas con 3 habitaciones" ,
  "Viviendas con 4 habitaciones" ,
  "Viviendas con 5 habitaciones" ,
  "Viviendas con 6 habitaciones" ,
  "Viviendas con 7 habitaciones" ,
  "Viviendas con 8 habitaciones" ,
  "Viviendas con 9 o más  habitaciones" ,
  "Total Hogares" ,
  "Total Hogares" ,
  "Hogares de 2 pers." ,
  "Hogares de 3 pers." ,
  "Hogares de 4 pers." ,
  "Hogares de 5 pers." ,
  "Hogares de 5 pers." )
shinyUI(fluidPage(
  navbarPage("DATOS MÁLAGA", id= "nav", theme = shinytheme("cerulean"),
    
    tabPanel("Mapa Interactivo",
             div(class="outer", 
                 tags$head(
                   includeCSS("styles.css"),
                   #includeScript("gomap.js")
                 ),
                 #in this new page, first plot me a nice big map
                 # leafletOutput("map1", width = "100%", height = 1000),
                 leafletOutput("map1", width = "100%", height = "100%"),
                 #then, create me a nice floaty panel which has all of the options in in, plus 
                 #a histogram of the variables selected
                 absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                               draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto",
                               width = 330, height = "auto",
                               #gimme a title
                               # h2("Datos Málaga"),
                                #gimme a drop down to select variables from the ward 
                               #boundaries dataset
                               selectInput("variable", "Attribute",
                                           names(wardBoundaries@data)[3:108]),
                                           # nombres),
                               #gimme some colour options from colourbrewer
                               selectInput("colourbrewerpalette", "Color Scheme",
                                           #rownames(subset(brewer.pal.info, category %in% c("seq", "div")))
                                           #just select those sequetinal palettes which we most liked 
                                           c("Blues","Greens","Oranges","Purples","Reds","OrRd","YlGn","YlOrRd")),
                               selectInput("classIntStyle", "Interval Style",
                                           c("Jenks Natural Breaks" = "jenks",
                                             "Quantile" = "quantile",
                                             "Equal Interval" = "equal",
                                             "Pretty" = "pretty")),
                               #plot me a nice plotly histogram
                               #plotlyOutput("plot1")
                               plotOutput("plot1")
                 )
              )
    ),
    tabPanel("Meta Data",
             # h2("Under Construction: explanation of variables and data manipulation"),
             #  h4("link to data; tables "),
             # includeHTML("metaData.html")
             h3("Under Construction"),
             
             hr(),
             h4(strong("Raw Data")),
             h5("Sección Censal"),
             p("It refers to the smallest administrative census section for which data is available. Find the shapefile", a(href="https://datosabiertos.malaga.eu/dataset/sistema-de-informacion-cartografica-seccion-censal", "here"),
               "for Málaga. However they are also avaiable in", a(href="https://datosabiertos.malaga.eu/dataset/plano-de-distritos-y-secciones-censales/resource/bb18ef25-bbac-4141-9330-c6d48c8e35c7", 
                                                                  "pfd"),"format." ),
             
             
             
            
             h5("Distrito"),

             h5("Distrito postal"),

             h5("Datos del padrón"),
             p("It refers to the municipal register data. Find the data in CSV format ", a(href="https://datosabiertos.malaga.eu/dataset/padron-de-habitantes-por-distrito-y-seccion-censal-2020", "here"),"for Málaga."),

             h5("Quick Tutorial INE web"),
             p("As the Instituto Nacional de Estadística (INE)",a(href="https://datosabiertos.malaga.eu/dataset/padron-de-habitantes-por-distrito-y-seccion-censal-2020", "website") ,"is quite difficult to understand, the aim here is to include a small guide so you do not lose as much time as I have lost."),
             h4(strong("Processed Data")),
             p("You may also find the processed data in a single shapefile on my", a(href="https://github.com/InigoMingolarra","Github folder"),"."),
             hr(),
             h3(strong("Attributes")),
             
             p(strong("distrit"),"Número distrito"),
             p(strong("seccion"),"Sección censal"),
             p(strong("poblacn"),"Población"),
             p(strong("AreaKm2"),"Area en Km^2 de la sección censal."),
             p(strong("Dn_px_2"),"Densidad de población en pers/Km^2"),
             p(strong("NUMDPOS"),"Código postal"),
             p(strong("NOMBRE"),"Nombre distrito"),
             p(strong("TotPobl"),"Total población"),
             p(strong("X7"),"Total hombres"),
             p(strong("X8"),"Total mujeres"),
             p(strong("X9"),"Pers. de menos de 16 años"),
             p(strong("X10"),"Pers. entre 16 y 64 años"),
             p(strong("X11"),"Pers. con más de 64 años"),
             p(strong("X12"),"Pers. que han nacido en España"),
             p(strong("X20"),"Pers. con nacionalidad española que han nacido en España"),
             p(strong("X36"),"Pers. con nacionalidad Española"),
             p(strong("X37"),"Pers. con nacionalidad extranjera"),
             p(strong("X38"),"Hombres de menos de 16 años"),
             p(strong("X39"),"Hombres entre 16 y 64 años"),
             p(strong("X40"),"Hombres con más de 64 años"),
             p(strong("X41"),"Mujeres de menos de 16 años"),
             p(strong("X42"),"Mujeres entre 16 y 64 años"),
             p(strong("X43"),"Mujeres con más de 64 años"),
             p(strong("X44"),"Hombres con nacionalidad española"),
             p(strong("X45"),"Hombres con nacionalidad extranjera"),
             p(strong("X46"),"Mujeres con nacionalidad española"),
             p(strong("X47"),"Mujeres con nacionalidad extranjera"),
             p(strong("X48"),"Pers. de nacionalidad española de menos de 16 años"),
             p(strong("X49"),"Pers. de nacionalidad extranjera de menos de 16 años"),
             p(strong("X50"),"Pers. de nacionalidad española entre 16 y 64 años"),
             p(strong("X51"),"Pers. de nacionalidad extranjera entre 16 y 64 años"),
             p(strong("X52"),"Pers. de nacionalidad española con más de 64 años"),
             p(strong("X53"),"Pers. de nacionalidad extranjera con más de 64 años"),
             p(strong("X54"),"Pers. con estado civil soltero"),
             p(strong("X55"),"Pers. con estado civil casado"),
             p(strong("X56"),"Pers. con estado civil separado"),
             p(strong("X57"),"Pers. con estado civil divorciado"),
             p(strong("X58"),"Pers. con estado civil viudo"),
             p(strong("X74"),"Pers. analfabetas"),
             p(strong("X75"),"Pers. sin estudios"),
             p(strong("X76"),"Pers. con estudios de primer grado"),
             p(strong("X77"),"Pers. con estudios de segundo grado"),
             p(strong("X78"),"Pers. con estudios de tercer grado"),
             p(strong("X79"),"Pers. sin información sobre su nivel de estudios (menores de 16 años)"),
             p(strong("X80"),"Hombres analfabetos"),
             p(strong("X81"),"Mujeres analfabetas"),
             p(strong("X82"),"Hombres sin estudios"),
             p(strong("X83"),"Mujeres sin estudios"),
             p(strong("X84"),"Hombres con estudios de primer grado"),
             p(strong("X85"),"Mujeres con estudios de primer grado"),
             p(strong("X86"),"Hombres con estudios de segundo grado"),
             p(strong("X87"),"Mujeres con estudios de segundo grado"),
             p(strong("X88"),"Hombres con estudios de tercer grado"),
             p(strong("X89"),"Mujeres con estudios de tercer grado"),
             p(strong("X90"),"Hombres sin información sobre su nivel de estudios (menores de 16 años)"),
             p(strong("X91"),"Mujeres sin información sobre su nivel de estudios (menores de 16 años)"),
             p(strong("X92"),"Mujeres sin información sobre su nivel de estudios (menores de 16 años)"),
             p(strong("X93"),"Pers. de nacionalidad extranjera y analfabetas"),
             p(strong("X94"),"Pers. de nacionalidad espaÃ±ola sin estudios"),
             p(strong("X95"),"Pers. de nacionalidad extranjera sin estudios"),
             p(strong("X96"),"Pers. de nacionalidad extranjera sin estudios"),
             p(strong("X97"),"Pers. de nacionalidad extranjera con estudios de primer grado"),
             p(strong("X98"),"Pers. de nacionalidad española con estudios de segundo grado"),
             p(strong("X99"),"Pers. de nacionalidad española con estudios de segundo grado"),
             p(strong("X100"),"Pers. de nacionalidad española con estudios de tercer grado"),
             p(strong("X101"),"Pers. de nacionalidad extranjera con estudios de tercer grado"),
             p(strong("X102"),"Pers. de nacionalidad española sin información sobre su nivel de estudios (menores de 16 años)"),
             p(strong("X110"),"Pers. entre 16 y 64 años con estudios de segundo grado"),
             p(strong("X111"),"Pers. con más de 64 años con estudios de segundo grado"),
             p(strong("X112"),"Pers. entre 16 y 64 años con estudios de tercer grado"),
             p(strong("X113"),"Pers. con más de 64 años con estudios de tercer grado"),
             p(strong("X114"),"Pers. de menos de 16 años (no se dispone de información sobre su nivel de estudios)"),
             p(strong("TtVvnds"),"Total Viviendas"),
             p(strong("X116"),"Viviendas Principales"),
             p(strong("VvndScn"),"Viviendas Secundarias"),
             p(strong("VivndVc"),"Viviendas Vacías"),
             p(strong("X119"),"Viviendas en propiedad, por compra, totalmente pagada"),
             p(strong("X120"),"Viviendas en propiedad, por compra, con pagos pendientes"),
             p(strong("X121"),"Viviendas en propiedad, por herencia o donación"),
             p(strong("VvndAlq"),"Viviendas en alquiler"),
             p(strong("X123"),"Viviendas cedida gratis o a bajo precio"),
             p(strong("X124"),"Viviendas en otro tipo de régimen de tenencia"),
             p(strong("X125"),"Viviendas de menos de 30m2"),
             p(strong("X126"),"Viviendas entre 30-45 m2"),
             p(strong("X127"),"Viviendas entre 46-60 m2"),
             p(strong("X128"),"Viviendas entre 61-75 m2"),
             p(strong("X129"),"Viviendas entre 76-90 m2"),
             p(strong("X130"),"Viviendas entre 76-90 m2"),
             p(strong("X131"),"Viviendas entre 106-120 m2"),
             p(strong("X132"),"Viviendas entre 121-150 m2"),
             p(strong("X133"),"Viviendas entre 121-150 m2"),
             p(strong("X134"),"Viviendas de más de 180 m2"),
             p(strong("X135"),"Viviendas con 1 habitación"),
             p(strong("X136"),"Viviendas con 2 habitaciones"),
             p(strong("X137"),"Viviendas con 3 habitaciones"),
             p(strong("X138"),"Viviendas con 4 habitaciones"),
             p(strong("X139"),"Viviendas con 5 habitaciones"),
             p(strong("X140"),"Viviendas con 6 habitaciones"),
             p(strong("X141"),"Viviendas con 7 habitaciones"),
             p(strong("X142"),"Viviendas con 8 habitaciones"),
             p(strong("X143"),"Viviendas con 9 o más  habitaciones"),
             p(strong("TotHgrs"),"Total Hogares"),
             p(strong("X145"),"Total Hogares"),
             p(strong("X146"),"Hogares de 2 pers."),
             p(strong("X147"),"Hogares de 3 pers."),
             p(strong("X148"),"Hogares de 4 pers."),
             p(strong("X149"),"Hogares de 5 pers."),
             p(strong("X150"),"Hogares de 5 pers.")
           

    ),
    tabPanel("Story Telling",
             h3("Under Construction"),
             hr(),
             h6("This work was done during the quarantine, around March or April of the pre-COVID era. The motivation behind was to showcase publicly the actual 
             available data in the municipal register in its smallest administrative units. Also to suggest the addition of other urban data as park area squared metres, 
             number of bus stops and average frequencies, average widths of sidewalks or other commercial data which with some basic geoprocessing may be quickly added.

             "),
             h6("The rationale of this work is to search and think for different possible uses of the data. In addtion to understand the importance of the breaks in a histogram"),

             hr(),
             h6("The processed data and scripts to build de the app are avaialable in my" , a(href="https://github.com/InigoMingolarra","Github folder"),
             ". However, they are based in Adam Dennet's", a(href="https://rpubs.com/adam_dennett/443357", "works") ,  "."),
             h6("Suggestions for possible improvements or uses are pretty much welcome."),
             h6("You may contact me in the following emai: imingolarra@gmail.com ")

             # source("storyTelling.html")
    )
  )
))
#length(names(wardBoundaries@data))
